[package]
name = "youtube_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
reqwest = "0.12.22"
serenity = "0.12.4"
songbird = { version = "0.5.0", default-features = true }
tokio = {version = "1.46.1", features = ["macros", "rt-multi-thread"] }
yt-dlp = "1.3.4"
